{% set name = "pyopenbt" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyopenbt-{{ version }}.tar.gz
  sha256: 111caf73073c397c531b68b2ded50c5f4a2b751b14a3dd4c4c546a9f54318362

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matplotlib-base
    - joblib

test:
  imports:
    - pyopenbt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cavan33/openbt_py
  summary: python interface to openbt
  license: GPL-2.0-or-later
  license_file: LICENSE
  description: |
    This Python package is the Python interface for Dr. Matthew Pratola's 
    OpenBT project (https://bitbucket.org/mpratola/openbt/wiki/Home). 

extra:
  recipe-maintainers:
    - jdtuck
